package tlssession

import (
	"fmt"
	"strings"

	tls "github.com/refraction-networking/utls"
)

// tlsCipherNames maps OpenVPN IANA names and OpenSSL short names to uTLS uint16
// IDs. Only ciphers present in the hardcoded vpnClientHelloHex fingerprint are
// listed; any other name is rejected at parse time.
var tlsCipherNames = map[string]uint16{
	// TLS 1.3 (OpenVPN IANA names)
	"TLS-AES-256-GCM-SHA384":      tls.TLS_AES_256_GCM_SHA384,
	"TLS-CHACHA20-POLY1305-SHA256": tls.TLS_CHACHA20_POLY1305_SHA256,
	"TLS-AES-128-GCM-SHA256":      tls.TLS_AES_128_GCM_SHA256,

	// ECDHE-ECDSA (IANA names)
	"TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384":       tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
	"TLS-ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256": tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
	"TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256":       tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
	"TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA384":       tls.DISABLED_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,
	"TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA":          tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
	"TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA":          tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,

	// ECDHE-RSA (IANA names)
	"TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384":       tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
	"TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256": tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
	"TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256":       tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	"TLS-ECDHE-RSA-WITH-AES-256-CBC-SHA384":       tls.DISABLED_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,
	"TLS-ECDHE-RSA-WITH-AES-256-CBC-SHA":          tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
	"TLS-ECDHE-RSA-WITH-AES-128-CBC-SHA":          tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,

	// DHE-RSA (IANA names; fake/stub in uTLS — included in ClientHello only)
	"TLS-DHE-RSA-WITH-AES-256-GCM-SHA384":       tls.FAKE_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,
	"TLS-DHE-RSA-WITH-CHACHA20-POLY1305-SHA256": uint16(0xccaa), // no named uTLS constant
	"TLS-DHE-RSA-WITH-AES-128-GCM-SHA256":       tls.FAKE_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
	"TLS-DHE-RSA-WITH-AES-256-CBC-SHA256":       tls.FAKE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,
	"TLS-DHE-RSA-WITH-AES-128-CBC-SHA256":       tls.FAKE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,
	"TLS-DHE-RSA-WITH-AES-256-CBC-SHA":          tls.FAKE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
	"TLS-DHE-RSA-WITH-AES-128-CBC-SHA":          tls.FAKE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA,

	// OpenSSL short names
	"ECDHE-ECDSA-AES256-GCM-SHA384": tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
	"ECDHE-ECDSA-CHACHA20-POLY1305": tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
	"ECDHE-ECDSA-AES128-GCM-SHA256": tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
	"ECDHE-ECDSA-AES256-SHA384":     tls.DISABLED_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,
	"ECDHE-ECDSA-AES256-SHA":        tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
	"ECDHE-ECDSA-AES128-SHA":        tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
	"ECDHE-RSA-AES256-GCM-SHA384":   tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
	"ECDHE-RSA-CHACHA20-POLY1305":   tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
	"ECDHE-RSA-AES128-GCM-SHA256":   tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	"ECDHE-RSA-AES256-SHA384":       tls.DISABLED_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,
	"ECDHE-RSA-AES256-SHA":          tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
	"ECDHE-RSA-AES128-SHA":          tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
	"DHE-RSA-AES256-GCM-SHA384":     tls.FAKE_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,
	"DHE-RSA-CHACHA20-POLY1305":     uint16(0xccaa), // no named uTLS constant
	"DHE-RSA-AES128-GCM-SHA256":     tls.FAKE_TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
	"DHE-RSA-AES256-SHA256":         tls.FAKE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,
	"DHE-RSA-AES128-SHA256":         tls.FAKE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,
	"DHE-RSA-AES256-SHA":            tls.FAKE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
	"DHE-RSA-AES128-SHA":            tls.FAKE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
}

// parseTLSCipherList converts a colon-separated OpenVPN cipher list string into
// a slice of uTLS uint16 IDs. Returns ErrBadTLSInit wrapping an error if any
// name is unrecognized. The renegotiation SCSV (0x00ff) is always appended.
func parseTLSCipherList(s string) ([]uint16, error) {
	names := strings.Split(s, ":")
	ids := make([]uint16, 0, len(names)+1)
	for _, name := range names {
		name = strings.TrimSpace(name)
		id, ok := tlsCipherNames[name]
		if !ok {
			return nil, fmt.Errorf("%w: unrecognized TLS cipher %q", ErrBadTLSInit, name)
		}
		ids = append(ids, id)
	}
	ids = append(ids, tls.FAKE_TLS_EMPTY_RENEGOTIATION_INFO_SCSV)
	return ids, nil
}
